name: Terraform Apply to Test Workspace
on: 
  workflow_dispatch:

# Set defaults
defaults:
  run:
    shell: bash

jobs:
  generate-matrix:
    # See https://github.community/t/check-pushed-file-changes-with-git-diff-tree-in-github-actions/17220/10 for the 
    #   source of this block of code. The first job builds the matrix of folders with terraform changes.
    name: Generate matrix for tf apply to Test workspace
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Check changed files
        id: diff
        # The messy awk/sed/grep filter after the git diff command is intended to force this to only list subfolders of
        #   ./apps/ and the ./shared/network for processing with the "test" workspace.
        run: |
          if [ $GITHUB_BASE_REF ]; then
            # Pull Request
            git fetch origin $GITHUB_BASE_REF --depth=1
            export DIFF=$( git diff --dirstat=files,0,cumulative origin/$GITHUB_BASE_REF $GITHUB_SHA | awk -F ' ' '{print $2}' | sed 's:/*$::' | grep -E '(^shared/n|^apps/)' )
            echo "PR Diff between origin/$GITHUB_BASE_REF and $GITHUB_SHA"
          else
            # Push
            git fetch origin ${{ github.event.before }} --depth=1
            export DIFF=$( git diff --dirstat=files,0,cumulative ${{ github.event.before }} $GITHUB_SHA | awk -F ' ' '{print $2}' | sed 's:/*$::' | grep -E '(^shared/n|^apps/)' )
            echo "Push Diff between ${{ github.event.before }} and $GITHUB_SHA"
          fi
          echo "$DIFF"
          # Escape newlines (replace \n with %0A)
          echo "::set-output name=diff::$( echo "$DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )"
      - name: Set matrix for build
        # This block actually creates the matrix. See https://stackoverflow.com/a/62953566/11948346 for the original source of
        #   this code. It sets two variables, DIFF and JSON, and then loops through the lines, only adding entries if it doesn't
        #   already exist. Finally, it removes the trailing comma and adds the closing brackets with the result being a properly
        #   formatted matrix for the next job.
        id: set-matrix
        run: |
          DIFF="${{ steps.diff.outputs.diff }}"
          JSON="{\"tfpaths\":["

          while read path; do
            JSONline="\"$path\","
            if [[ "$JSON" != *"$JSONline"* ]]; then
              JSON="$JSON$JSONline"
            fi
          done <<< "$DIFF"

          if [[ $JSON == *, ]]; then
            JSON="${JSON%?}"
          fi
          JSON="$JSON]}"
          echo $JSON

          echo "::set-output name=matrix::$( echo "$JSON" )"

  tfpromote:
    # Set workflow environment variables
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PIPENV_PIPFILE: ../../scripts/Pipfile
      TF_WORKSPACE: dev
    
    # This splits out a matrix of jobs that processes each of the folders with updates to terraform code.
    name: Run Terraform Apply on "${{ matrix.tfpaths }}"
    needs: generate-matrix
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo first
      - name: Checkout
        uses: actions/checkout@v2

      # Setup terraform with the correct version
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.7

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Create the terraform.tfvars file. This expects that all the commands are run in subfolders
      #   that are two (2) folders deep in the repository. It also depends on the PIPENV_PIPFILE environment
      #   variable, the TF_WORKSPACE environment variable, and the GITHUB_HEAD_REF default environment variable.
      #   The end result of this step is a correct terraform.tfvars file.
      - name: Create tfvars
        run: |
          echo "working directory = ${{ matrix.tfpaths }}/"
          pip install pipenv
          pipenv install
          pipenv run python ../../scripts/parameter_export.py -p ${{ matrix.tfpaths }} -b ${GITHUB_HEAD_REF}
        working-directory: ${{ matrix.tfpaths }}/

      # Run Terraform Apply for test environment
      - name: Terraform Promote to Test
        id: tfapplytest
        run: |
          echo "${{ matrix.tfpaths }}"
          terraform init -backend-config=../../backend.hcl
          terraform apply -auto-approve -no-color -var-file=terraform.tfvars
        working-directory: ${{ matrix.tfpaths }}/
        continue-on-error: true
      
      # Publish the plan output in the Pull Request for test workspace
      - name: output 
        uses: actions/github-script@v3
        env:
          PLAN: "terraform\n${{ steps.tfplantest.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Plan 📖\`${{ steps.tfplantest.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`${process.env.PLAN}\`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      # Proper exit status for failed terraform plan in the test environment
      - name: Terraform Promote to Test Status
        if: steps.tfplantest.outcome == 'failure'
        run: exit 1